### ISSUE TITLE
Support for *varargs and **kwargs

### ISSUE THREAD

**Issue by Snooz82** [imbus/testbench2robotframework#1]
libdoc2testbench imports *varargs, **kwargs and named arguements with the prefix of `*${SPACE}`, `**${SPACE}` and `-${SPACE}` and therefore this should also be supported by TestBench2RobotFramework.

**varargs**
- [x] The `${SPACE}` should be optinal
- [x] when a `*vararg` is given, no "double_space_escaping` shall be performed.

**kwargs**
- [x] The `${SPACE}` should be optinal
- [x]  when a `**vararg` is given, no "double_space_escaping" and no "equal_sign_escaping" shall be performed.

**named args**
- [x] if previous argument was a vararg or named argument, or no value was specified the following arguments must be named
- [x] the arguemnt name does start with `-${SPACE}` (`${SPACE}` is optional) or does end with an `=` testbench2robotframework should pass it as an named argument

**Comment by HenrikSchuette** [comment]
Added in version 0.5.2
